### ISSUE TITLE
Telling av stemmer

### ISSUE THREAD

**Issue by Neelzee** [Neelzee/Dat250Project#3]
# Forslag

Eg trur det ville vært betre om vi endrar database modellen vår, slik at vi registrerar stemmar, ved å i staden for å auka ein teljar, at vi har ei tabell av alle som har stemt.

## Eksempel på løysning

Den kan sjå noko ut som dette:

| VoteId | PollId | VoteCount | Choice | RegisteredVoterId |
| -------- | -------- | -------------- | ---------- |------------------------ |
| 1         | 1        | 1                | 0          | 1                            |  
| 2         | 4        | 5                | 1          | Null                       | 

Første raden er ei som har stemt ifrå nettsida, mens andre rad er eit IOT einheit.

Då får vi det beste av begge verdner, `Poll`-tabellen, kan framleis ha ein counter, som vi brukar for _real time_ stemme teljing.

Men me sleppe også problemmet, ved at vi må prosessere ein haug med stemmer, vi kan oppdatera `Poll`-tabellen sin counter avhengig av trafikken eit `Val` får.

**Comment by h586613** [comment]
kjør på
